lib/todoElixir_web/router.ex
defmodule TodoElixirWeb.Router do
  use TodoElixirWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :auth do
    plug(TodoElixir.Pipeline)
  end

  pipeline :ensure_auth do
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", TodoElixirWeb do
    # Use the default browser stack
    pipe_through([:browser, :auth])

    get("/", PageController, :index)

    resources("/users", UserController)
  end

  scope "/session", TodoElixirWeb do
    pipe_through([:browser, :auth])
    get("/new", SessionController, :new)
    post("/login", SessionController, :login)
  end

  scope "/", TodoElixirWeb do
    pipe_through([:browser, :auth, :ensure_auth])
    get("/todos", TodoController, :index)
    delete("/session/logout", SessionController, :logout)
  end

  #  scope "/", TodoElixirWeb do
  #    pipe_through([:browser, :auth])
  #
  #    resources("/users", UserController, only: [:edit, :update, :show])
  #  end

  # Other scopes may use custom stacks.
  # scope "/api", TodoElixirWeb do
  #   pipe_through :api
  # end
end

lib/todoElixir/application.ex
defmodule TodoElixir.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(TodoElixir.Repo, []),
      # Start the endpoint when the application starts
      supervisor(TodoElixirWeb.Endpoint, []),
      # Start your own worker by calling: TodoElixir.Worker.start_link(arg1, arg2, arg3)
      # worker(TodoElixir.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: TodoElixir.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    TodoElixirWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/todoElixir/auth.ex
defmodule TodoElixir.Auth do
  alias Comeonin.Bcrypt
  alias TodoElixir.{Repo, User}

  import Ecto.Query

  def authenticate_user(email, plain_password) do
    query = from(u in User, where: u.email == ^email)

    case Repo.one(query) do
      nil ->
        Bcrypt.dummy_checkpw()
        {:error, :invalid_credentials}

      user ->
        if(Bcrypt.checkpw(plain_password, user.password_hash)) do
          {:ok, user}
        else
          {:error, :invalid_credentials}
        end
    end
  end
end

lib/todoElixir/repo.ex
defmodule TodoElixir.Repo do
  use Ecto.Repo, otp_app: :todoElixir

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/todoElixir/user.ex
defmodule TodoElixir.User do
  use Ecto.Schema
  import Ecto.Changeset

  alias TodoElixir.Repo
  alias Comeonin.Bcrypt

  schema "users" do
    field(:email, :string)
    field(:password, :string, virtual: true)
    field(:password_hash, :string)
    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email, :password_hash])
    |> validate_required([:email])
    |> unique_constraint(:email)
    |> validate_format(:email, ~r/@/)
  end

  def registration_changeset(struct, params \\ %{}) do
    struct
    |> changeset(params)
    |> cast(params, [:password])
    |> validate_length(:password, min: 5)
    |> put_password_hash()
  end

  def get_user(id) do
    Repo.get(__MODULE__, id)
  end

  defp put_password_hash(%Ecto.Changeset{valid?: true, changes: %{password: pass}} = struct) do
    put_change(struct, :password_hash, Bcrypt.hashpwsalt(pass))
  end

  defp put_password_hash(struct), do: struct
end

lib/todoElixir_web/controllers/page_controller.ex
defmodule TodoElixirWeb.PageController do
  use TodoElixirWeb, :controller
  alias TodoElixir.{Repo, User, Guardian}

  def index(conn, _params) do
    users = Repo.all(User)
    user = Guardian.Plug.current_resource(conn)
    IO.inspect(user)
    render(conn, "index.html", users: users, current_user: user)
  end
end

lib/todoElixir_web/controllers/session_controller.ex
defmodule TodoElixirWeb.SessionController do
  use TodoElixirWeb, :controller

  alias TodoElixir.{User, Auth, Guardian}

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    maybe_user = Guardian.Plug.current_resource(conn)

    if maybe_user do
      conn
      |> redirect("/")
    else
      conn
      |> render("new.html", changeset: changeset, action: session_path(conn, :login))
    end
  end

  def login(conn, %{"user" => %{"email" => email, "password" => password}}) do
    Auth.authenticate_user(email, password)
    |> login_reply(conn)
  end

  def login_reply({:ok, user}, conn) do
    conn
    |> put_flash(:success, "Welcome back!")
    |> Guardian.Plug.sign_in(user)
    |> redirect(to: "/")
  end

  def login_reply({:error, reason}, conn) do
    conn
    |> put_flash(:error, to_string(reason))
    |> new(%{})
  end

  def logout(conn, _params) do
    conn
    |> Guardian.Plug.sign_out()
    |> redirect(to: "/")
  end
end

lib/todoElixir_web/controllers/todo_controller.ex
defmodule TodoElixirWeb.TodoController do
  use TodoElixirWeb, :controller

  alias TodoElixir.User
end

lib/todoElixir_web/controllers/user_controller.ex
defmodule TodoElixirWeb.UserController do
  use TodoElixirWeb, :controller

  alias TodoElixir.{Repo, User}

  def new(conn, _params) do
    changeset = User.changeset(%User{})

    conn
    |> render("new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.registration_changeset(%User{}, user_params)
    IO.inspect(changeset)

    case Repo.insert(changeset) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "User created")
        |> redirect(to: page_path(conn, :index))

      {:error, changeset} ->
        conn
        |> render("new.html", changeset: changeset)
    end
  end

  def edit(conn, %{"id" => id} = params) do
    user = Repo.get(User, id)
    changeset = User.changeset(user)

    conn
    |> render("edit.html", changeset: changeset, user: user)
  end

  def update(conn, %{"id" => user_id, "user" => user_params} = params) do
    user =
      User
      |> Repo.get(user_id)

    changeset = User.registration_changeset(user, user_params)
    IO.inspect(changeset)

    conn
    |> render("edit.html", changeset: changeset, user: user)
  end

  def show(conn, %{"id" => id}) do
    user = Repo.get(User, id)

    conn
    |> render("show.html", user: user)
  end
end

lib/todoElixir_web/views/error_view.ex
defmodule TodoElixirWeb.ErrorView do
  use TodoElixirWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/todoElixir_web/views/layout_view.ex
defmodule TodoElixirWeb.LayoutView do
  use TodoElixirWeb, :view
end

lib/todoElixir_web/views/page_view.ex
defmodule TodoElixirWeb.PageView do
  use TodoElixirWeb, :view
end

lib/todoElixir_web/views/session_view.ex
defmodule TodoElixirWeb.SessionView do
  use TodoElixirWeb, :view
end

lib/todoElixir_web/views/user_view.ex
defmodule TodoElixirWeb.UserView do
  use TodoElixirWeb, :view
end

lib/todoElixir_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello TodoElixir!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <a href="<%= page_path(@conn, :index) %>"><span class="logo"></span></a>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/todoElixir_web/templates/page/index.html.eex
<%= if @current_user do %>
<h1>Welcome Back <%= @current_user.email %></h1>
<% end %>
<ul>
  <%= for user <- @users do %>
  <li>  <%= user.email %> - <%= link "View", to: user_path(@conn, :show, user) %></li>
  <% end %>
</ul>
<%= if !@current_user do %>
  <a href="<%= user_path(@conn, :new) %>">Sign Up</a>
  <a href="<%= session_path(@conn, :new) %>">Login</a>
<% else %>
  <%= link "Logout", to: session_path(@conn, :logout), method: :delete %>
<%end %>

lib/todoElixir_web/templates/session/new.html.eex
<%= form_for @changeset, @action, fn f -> %>
    <div class="form-group">
        <%= label f, :email, class: "control-label" %>
        <%= text_input f , :email, class: "form-control" %>
        <%= error_tag f, :email %>
    </div>

    <div class="form-group">
        <%= label f, :password, class: "control-label" %>
        <%= password_input f , :password, class: "form-control" %>
        <%= error_tag f, :password %>
    </div>

    <div class="form-group">
        <%= submit "Submit", class: "btn btn-primary" %>
    </div>
<% end %>

lib/todoElixir_web/templates/user/edit.html.eex
<h1>Edit user</h1>
<%= form_for @changeset, user_path(@conn, :update, @user), fn f -> %>
    <%= render TodoElixirWeb.UserView, "form.html", f: f %>
    <%= submit "Edit", class: "btn btn-primary" %>
<% end %>

lib/todoElixir_web/templates/user/form.html.eex
<div class="form-group">
    <%= text_input @f, :email, placeholder: "Email", class: "form-control" %>
    <%= error_tag @f, :email %>
</div>
<div class="form-group">
    <%= password_input @f, :password, placeholder: "Password", class: "form-control" %>
    <%= error_tag @f, :password %>
</div>

lib/todoElixir_web/templates/user/new.html.eex
<h1>Create a user</h1>
<%= form_for @changeset, user_path(@conn, :create), fn f -> %>
    <%= render TodoElixirWeb.UserView, "form.html", f: f %>
    <%= submit "Create", class: "btn btn-primary" %>
<% end %>

lib/todoElixir_web/templates/user/show.html.eex
<h1><%= @user.email %></h1>
<div>
    <%= link "Edit", to: user_path(@conn, :edit, @user) %>
</div>